# Generated by Django 3.1.3 on 2020-11-16 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0002_auto_20201116_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='exp_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 16, 0, 11, 33, 789253)),
        ),
    ]
