# Generated by Django 3.1.3 on 2020-11-16 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0003_auto_20201116_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='pin',
            field=models.PositiveIntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='exp_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 16, 1, 19, 26, 130573)),
        ),
    ]
