# Generated by Django 3.1.3 on 2020-11-16 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0004_auto_20201116_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='atm_machine',
            name='address',
            field=models.CharField(default='Group 1', max_length=30),
        ),
        migrations.AddField(
            model_name='atm_machine',
            name='status',
            field=models.CharField(default='Active', max_length=30),
        ),
        migrations.AlterField(
            model_name='card',
            name='exp_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 16, 5, 8, 29, 250725)),
        ),
    ]
