# Generated by Django 3.1.3 on 2020-11-16 12:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0009_auto_20201116_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='account_number',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ATM.account'),
        ),
        migrations.AlterField(
            model_name='card',
            name='exp_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 16, 7, 48, 8, 120177)),
        ),
    ]
