# Generated by Django 3.1.3 on 2020-11-16 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0014_auto_20201116_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='exp_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 16, 10, 27, 0, 933577)),
        ),
        migrations.AlterField(
            model_name='card',
            name='pin',
            field=models.PositiveIntegerField(default=False),
        ),
    ]
