# Generated by Django 3.1.3 on 2020-11-16 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0015_auto_20201116_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='account_number',
        ),
        migrations.AddField(
            model_name='card',
            name='card_status',
            field=models.CharField(default='Active', max_length=30),
        ),
        migrations.AlterField(
            model_name='card',
            name='exp_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 16, 11, 59, 56, 759611)),
        ),
    ]
