# Generated by Django 3.1.3 on 2020-11-16 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0016_auto_20201116_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='exp_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 16, 12, 0, 32, 329309)),
        ),
    ]
